#!/usr/bin/env python3.6
# -*- coding=utf-8 -*-

import argparse
import colorama
import json
import readline
import sys

from pecan.lang.lark.parser import UnexpectedToken

import spot

from pecan import program

from pecan.settings import settings

from pecan import utility

pecan_version = '1.1.2'
intended_python_version = '3.14.4'
intended_spot_version = '2.15.1'

def run_repl(env):
    from pecan.logger import Logger
    utility.touch(settings.get_history_file())
    readline.read_history_file(settings.get_history_file())

    while True:
        try:
            prog_str = input('> ').strip()

            if prog_str.lower() == 'exit':
                break

            if prog_str.startswith(':set'):
                parts = prog_str.split(' ')
                if len(parts) > 1:
                    if parts[1] == 'debug':
                        settings.set_debug_level(1 if settings.get_debug_level() <= 0 else 0)
            else:
                prog = program.from_source(prog_str)
                Logger.log(str(prog), 0)
                prog.include_with_restrictions(env)
                env = prog.evaluate_prog()
        except KeyboardInterrupt:
            print('') # newline to go "below" the prompt
            print("Use 'exit' to exit Pecan.")
        except EOFError:
            print('exit')
            break
        except UnexpectedToken as e:
            print(e)
        except Exception as e:
            Logger.error('An exception occured: {}'.format(e))

            if settings.debug_level > 0: # Swallowing the error is bad for debugging purposes, so we print the traceback if using debug mode
                import traceback
                traceback.print_exc()

    readline.write_history_file(settings.get_history_file())

    return env

def main():
    parser = argparse.ArgumentParser(description='An automated theorem prover for Büchi Automata')
    parser.add_argument('file', help='A Pecan file to execute', nargs='?')
    parser.add_argument('-v', '--version', help='Show the current version of Pecan being used and exit', required=False, action='store_true')
    parser.add_argument('-i', '--interactive', help='Run Pecan in interactive mode (REPL)', required=False, action='store_true')
    parser.add_argument('-d', '--debug', help='Output debugging information', required=False, action='count')
    parser.add_argument('-q', '--quiet', help='Quiet mode', required=False, action='store_true')
    parser.add_argument('--no-opt', help='Turns off optimizations', required=False, action='store_true')
    parser.add_argument('--min-opt', help='Set optimizations to minimal levels (only boolean and arithmetic optimizations).', required=False, action='store_true')
    parser.add_argument('--no-stdlib', help='Turns off the default behavior of loading the standard library (from library/std.pn in your Pecan installation)', required=False, action='store_false')
    parser.add_argument('--heuristics', help='Use heuristics to determine how to simplify automata. This flag is typically useful with large automata (>10000 states), and can cause worse performance with smaller automata.', required=False, action='store_true')
    parser.add_argument('--postprocessing-preference', help='Which automaton characteristic should be preferred when postprocessing automata if heuristics are disabled. Can be either "Small" or "Deterministic", defaults to "Small".', required=False, type=str, metavar='PREFERENCE', choices=['Small', 'Deterministic'], default='Small')
    parser.add_argument('--postprocessing-force-sbacc', help='Enforce automaton postprocessing to produce Büchi automata with state-based acceptance. May slow down postprocessing is some cases.', required=False, action='store_true')
    parser.add_argument('--extract-implications', help='Alternate mode of running a program involving going through each theorem, extracting the top-level implication that needs to be checked (if applicable).', required=False, action='store_true')
    parser.add_argument('--use-var-map', help='Use the var_map from the specified file and convert the main file to use the same var map (i.e., the argument corresponding to <file>)', required=False, type=str)
    parser.add_argument('--stats', help='Write out statistics about each predicate defined and theorem tested (i.e., in save_aut and assert_prop)', required=False, action='store_true')
    parser.add_argument('--output-hoa', help='Outputs encountered Buchi automata into the file', required=False, type=str, dest="output_hoa", metavar='HOA_FILE')
    parser.add_argument('--output-json', help='Write the output in a JSON format of {"stdout": str, "files": array of strings} where the files array is the names of all the files generated by the Pecan program to standard output when Pecan exists. Useful for running headless on a server to gather the result files.', required=False, action='store_true')
    parser.add_argument('--no-progress', help='Disables all progress bars/indicators. Quiet mode implies this option is on. Should use if planning to pipe output to a file.', required=False, action='store_true')
    parser.add_argument('--expand-definition', help='Take the name of a predicate loaded from the main file and expands all uses of intermediate predicates (i.e., predicates not loaded from files).', required=False, type=str, metavar='PREDICATE_NAME')

    args = parser.parse_args()

    if args.version:
        print('Pecan {}, made for Python {} and Spot {}'.format(pecan_version, intended_python_version, intended_spot_version))
        exit(0)

    settings.set_quiet(args.quiet)
    settings.set_opt_level(0 if args.no_opt else 1)
    settings.set_load_stdlib(args.no_stdlib)
    settings.set_use_heuristics(args.heuristics)
    settings.set_postprocessing_preference(args.postprocessing_preference)
    settings.set_postprocessing_force_sbacc(args.postprocessing_force_sbacc)
    settings.set_min_opt(args.min_opt)
    settings.set_extract_implications(args.extract_implications)
    settings.set_write_statistics(args.stats)
    settings.set_output_hoa(args.output_hoa)
    settings.set_output_json(args.output_json)
    settings.set_show_progress(not args.no_progress)

    if args.debug is None:
        settings.set_debug_level(0)
    else:
        settings.set_debug_level(args.debug)

    if args.use_var_map is not None:
        if args.file is None:
            print('If --use-var-map is specified, you must also specify <file>!')
            exit(1)

        from pecan.tools.hoa_loader import load_hoa
        use_var_map_aut = load_hoa(args.use_var_map)
        main_file_aut = load_hoa(args.file)

        ap_subs = {}
        for v, aps in use_var_map_aut.get_var_map().items():
            for main_ap, new_ap in zip(main_file_aut.get_var_map().get(v, []), aps):
                ap_subs[main_ap] = new_ap

        s = main_file_aut.aut.to_str('hoa')
        for a,b in ap_subs.items():
            s = s.replace(a, b)
        print(s)

        # print(ap_subs)
        # main_file_aut = main_file_aut.ap_substitute(ap_subs)
        # print(main_file_aut.to_str())

        return

    env = None
    prog = None
    if args.file is not None:
        try:
            prog = program.load(args.file)
            if not settings.get_extract_implications():
                env = prog.evaluate_prog()
        except UnexpectedToken as e:
            print(e)
            return None

    if args.expand_definition is not None:
        if prog is None:
            prog = program.from_source('')
            env = prog.evaluate_prog()
        
        from pecan.lang.predicate_expander import PredicateExpander
        from pecan.lang.ir.prog import Call
        pred = prog.lookup_pred_by_name(args.expand_definition)
        print('Expanding', pred)
        print(PredicateExpander(prog).transform(Call(pred.name, pred.args)))

    if args.interactive:
        if env is None:
            prog = program.from_source('')
            env = prog.evaluate_prog()

        prog = run_repl(env)
    elif args.file is None and args.expand_definition is None:
        parser.print_help()

    if settings.get_output_json():
        if prog is not None:
            print(json.dumps({'output': settings.get_output(), 'files': prog.get_generated_files()}))
        else:
            print(json.dumps({'output': '', 'files': []}))

if __name__ == '__main__':
    # Increase a little bit (default is 1000) because Praline is very inefficient.
    sys.setrecursionlimit(2000)

    colorama.init()
    spot.setup()
    main()

